### ISSUE TITLE
Why does this require the Ruby buildpack?

### ISSUE THREAD

**Issue by ivanvenosdel** [dscout/wkhtmltopdf-buildpack#12]
I see this line under the usage documentation:
> $ echo 'https://github.com/heroku/heroku-buildpack-ruby.git' >> .buildpacks

However I don't understand why Ruby specifically is necessary since neither your code or the wkhtmltopdf debian package requires Ruby.

I am wondering if you more have that line there as an example of using it alongside a site that is already using a Ruby build pack.

Is it safe to assume that I could replace that line with whatever build pack I am already using? If so, I might kick a quick pull request your way with a README update. :)

**Comment by sorentwo** [comment]
We just happened to be using it with a ruby build pack, there isn't any dependency on Ruby. Feel free to open a PR!

**Comment by ivanvenosdel** [comment]
Thanks! Will do. 

One other question. I don't know how recent it is but I am seeing that Heroku already supports [specifying multiple build packs](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app). What's the advantage of the one you list in the usage instructions?

Also I guess [BUILDPACK_URL is deprecated](https://devcenter.heroku.com/articles/buildpacks). 
> Previously you could set a config var for BUILDPACK_URL, this value will still be used if set, though a buildpack value set through the CLI will take precedence. BUILDPACK_URL as a config var is now deprecated in favor of the buildpack value on the API and in the future will be migrated.

**Comment by sorentwo** [comment]
I've updated the documentation to use `buildpacks:set` instead of `BUILDPACK_URL`, and to note that you don't need to use Ruby as part of the multi buildpack.

**Comment by ivanvenosdel** [comment]
Thanks! Sorry I didn't get to it sooner.
