### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by AdamBrodzinski** [dscout/wkhtmltopdf-buildpack#17]
Hello,

I'm trying to use this buildpack but cannot figure out how to execute wkhtmltopdf. If I try:

```
heroku run bash
wkhtmltopdf -V
bash: wkhtmltopdf: command not found
```

and if I check `/bin` , `wkhtmltopdf` is not there.

However the buildpack logs out when compiling the app:

```
 ...
-----> wkhtmltopdf-buildpack app detected
-----> Using wkhtmltopdf Debian package from cache
-----> Unpacking Debian package
-----> Setting permissions
-----> Moving binaries to the right place
-----> Cleaning up
-----> Installing fonts
wqy-microhei.ttc
wqy-zenhei.ttc
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 125.4M
-----> Launching...
       Released v108
```

Do you have any ideas of where I should start troubleshooting?

Thanks!

**Comment by sorentwo** [comment]
I haven't heard of this happening before. The buildpack output looks correct, and the binary should be available directly the way you are testing it.

To double check I opened a shell using the buildpack and the binary showed up. There may have been a temporary problem fetching the file and it stayed silent. That's my only guess currently.

**Comment by sorentwo** [comment]
@AdamBrodzinski Any luck getting this to work?

**Comment by AdamBrodzinski** [comment]
@sorentwo no dice, but I added https://github.com/rafaelp/heroku-buildpack-wkhtmltopdf and that buildpack's path works. Not sure why 🤔
