### ISSUE TITLE
Consider adding tags

### ISSUE THREAD

**Issue by fschwahn** [dscout/wkhtmltopdf-buildpack#21]
I just found this buildpack, and have a suggestion: add tags so it is possible to fix the wkhtmltopdf version. In the past wkhtmltopdf broke my PDFs after updates. If you'd add tags, these could be used in the `.buildpacks`-file, so nobody is accidentally updated.

Incidentally, 0.12.4 breaks my pdfs, so it would be great if there'd be a tag for 0.12.3

**Comment by sorentwo** [comment]
Since #25 you have been able to specify the version through an env var. This is more flexible than maintaining various tags, and it should satisfy your use case.
