### ISSUE TITLE
Make it work for new release 0.12.5

### ISSUE THREAD

**Issue by verheyenkoen** [dscout/wkhtmltopdf-buildpack#33]
A couple of days ago wkhtmltopdf 0.12.5 has been released. It turns out the buildpack doesn't work out-of-the-box when setting the version in config (the release url seems to have changed). Can you make the buildpack work for the new version?

**Comment by turicas** [comment]
I also maintain a wkhtmltopdf buildpack - this is a related issue: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3947#issuecomment-396650029

**Comment by sorentwo** [comment]
This should be fixed with https://github.com/dscout/wkhtmltopdf-buildpack/pull/36, though it doesn't appear to be in a mergeable state currently. Closing in favor of the PR.
